// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRjpxyx1A0N46b_CiKBSbNDvKGlRueGIE',
    appId: '1:556499424417:web:67929a61ba891036de4ce0',
    messagingSenderId: '556499424417',
    projectId: 'tiktok-clone2-22c60',
    authDomain: 'tiktok-clone2-22c60.firebaseapp.com',
    storageBucket: 'tiktok-clone2-22c60.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiBJLaY4jhCcxiaITCBTV2w5k1mk4fx0A',
    appId: '1:556499424417:android:963593e0ef199dc5de4ce0',
    messagingSenderId: '556499424417',
    projectId: 'tiktok-clone2-22c60',
    storageBucket: 'tiktok-clone2-22c60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdeY8GsfUUT1gmuOBc6K96Fj4uky5eMbM',
    appId: '1:556499424417:ios:30d36ac3517234f4de4ce0',
    messagingSenderId: '556499424417',
    projectId: 'tiktok-clone2-22c60',
    storageBucket: 'tiktok-clone2-22c60.appspot.com',
    iosClientId: '556499424417-mujpggb885sfks7rcoitdsoguo90aq11.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdeY8GsfUUT1gmuOBc6K96Fj4uky5eMbM',
    appId: '1:556499424417:ios:30d36ac3517234f4de4ce0',
    messagingSenderId: '556499424417',
    projectId: 'tiktok-clone2-22c60',
    storageBucket: 'tiktok-clone2-22c60.appspot.com',
    iosClientId: '556499424417-mujpggb885sfks7rcoitdsoguo90aq11.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTiktokClone',
  );
}
